spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/edusmart
    username: postgres
    password: 852456

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  data:
    redis:
      host: localhost
      port: 6379
